### ISSUE TITLE
Alice Todo

### ISSUE THREAD

**Issue by merunno** [AliceCinderella/Alice#8]
### コマンド

- [ ] `/ban <user> [reason]` -- 指定ユーザーをBANする
- [ ] `/kick <user> [reason]` -- 指定ユーザーをKickする
- [ ] `/timeout <user> <period> [reason]` -- 指定ユーザーをタイムアウトにする
- [ ] `/seen <user>` -- 指定ユーザーの最終アクティビティを確認する
- [ ] `/change <user> <reason>` -- 指定ユーザーに行われた処罰の理由変更
- [ ] `/change timeout#period <user> <period> <reason>` -- 指定ユーザーのタイムアウトの期間を変更
- [ ] `/unban <user> <reason>` -- 指定ユーザーのBANを解除
- [ ] `/unkick <user> <reason>` -- 指定ユーザーのKickを解除
- [ ] `/untimeout <user> <reason>` -- 指定ユーザーのタイムアウトを解除
- [ ] `/warn <user> [reason]` --　指定ユーザーを警告する (3つ貯まると強制タイムアウト)
- [ ] `/caution <user> <message> [reason]` -- 指定ユーザーに注意を行う。(DMに送信するため、送受信を制限されている場合はできない)
- [ ] `/warns` -- 警告状況の確認
- [ ] `/note <user> <note>` -- 指定ユーザーをノートする
- [ ] `/help` -- ヘルプを確認
- [ ] `/whois <user>` -- 指定ユーザーの処罰状況の確認
- [ ] `/user <user>` --　指定ユーザーの情報参照
- [ ] `/server` -- サーバーの情報参照
- [ ] `/role <role>` -- ロールの情報参照
- [ ] `/channel <channel>` -- チャンネルの情報参照
- [ ] `/set topic <channel> <topic>` -- チャンネルのトピックを設定
- [ ] `/event list` -- イベントのリスト参照
- [ ] `/event set#status <eventid> <status : SCHEDULED, ACTIVE, COMPLETED, CANCELED>` -- 指定イベントのステータスを変更
- [ ]  `/event set#cancel <eventid>` -- 指定イベントを強制キャンセル

### 機能

- [ ] トークン保護機能
